#!/usr/bin/env bash

set -Eeuo pipefail

log() { echo "[INFO] $*"; }
warn() { echo "[WARN] $*" >&2; }
err() { echo "[ERROR] $*" >&2; }

if [[ "${EUID}" -ne 0 ]]; then
  err "Run this script as root (sudo)."
  exit 1
fi

if ! command -v apt >/dev/null 2>&1; then
  err "This installer supports Debian/Ubuntu (apt) only."
  exit 1
fi

log "Installing Apache Guacamole + ser2net"

export DEBIAN_FRONTEND=noninteractive
apt update
apt upgrade -y
apt install -y docker.io docker-compose-plugin ser2net curl ca-certificates python3 python3-venv python3-pip rsync git openssl

if ! systemctl is-active --quiet docker; then
  systemctl enable --now docker
fi

read -r -p "Enter the number of devices (default 1): " NUM_DEVICES
NUM_DEVICES="${NUM_DEVICES:-1}"
if ! [[ "${NUM_DEVICES}" =~ ^[0-9]+$ ]] || [[ "${NUM_DEVICES}" -lt 1 ]]; then
  err "NUM_DEVICES must be a positive integer."
  exit 1
fi

read -r -s -p "Enter MYSQL_PASSWORD (for user guacamole_user): " MYSQL_PASSWORD
echo ""
read -r -s -p "Enter MYSQL_ROOT_PASSWORD: " MYSQL_ROOT_PASSWORD
echo ""

if [[ -z "${MYSQL_PASSWORD}" || -z "${MYSQL_ROOT_PASSWORD}" ]]; then
  err "MySQL passwords must not be empty."
  exit 1
fi

log "${NUM_DEVICES} devices will be configured"

install_dir="/opt/guacamole"
mkdir -p "${install_dir}"
cd "${install_dir}"

cat > docker-compose.yml <<EOF
services:
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      guacd:
        condition: service_started
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: guac-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - ./mysql_data:/var/lib/mysql
EOF

docker compose up -d

log "Waiting for MySQL healthcheck..."
for _ in $(seq 1 60); do
  if docker inspect -f '{{.State.Health.Status}}' guac-mysql 2>/dev/null | grep -q "healthy"; then
    break
  fi
  sleep 2
done

if ! docker inspect -f '{{.State.Health.Status}}' guac-mysql 2>/dev/null | grep -q "healthy"; then
  err "MySQL did not become healthy in time."
  exit 1
fi

if [[ ! -f initdb.sql ]]; then
  docker run --rm guacamole/guacamole:latest /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
fi
docker exec -i guac-mysql mysql -u root "-p${MYSQL_ROOT_PASSWORD}" guacamole_db < initdb.sql

cat > /etc/ser2net.yaml <<'EOF'
%YAML 1.1
---
EOF

for i in $(seq 1 "${NUM_DEVICES}"); do
  port=$((2000 + i))
  router_num="$(printf "%02d" "${i}")"
  cat >> /etc/ser2net.yaml <<EOF

connection: &Router${router_num}
  accepter: tcp,0.0.0.0,${port}
  connector: serialdev,/dev/ttyRouter${router_num},115200n81,local
EOF
done

systemctl enable --now ser2net
systemctl restart ser2net

cat > /etc/udev/rules.d/99-usb-serial.rules <<EOF
# Autogenerated for ${NUM_DEVICES} devices.
# Replace XXXX placeholders with real VID/PID/serial values.
EOF

for i in $(seq 1 "${NUM_DEVICES}"); do
  router_num="$(printf "%02d" "${i}")"
  cat >> /etc/udev/rules.d/99-usb-serial.rules <<EOF
SUBSYSTEM=="tty", ATTRS{idVendor}=="XXXX", ATTRS{idProduct}=="XXXX", ATTRS{serial}=="XXXX", SYMLINK+="ttyRouter${router_num}"
EOF
done

udevadm control --reload-rules
udevadm trigger

log "Deploying Lab Portal service"
read -r -p "Install Lab Portal from GitHub URL? (leave empty to use local files): " LAB_PORTAL_GIT_URL

portal_dir="/opt/guac-lab-portal"
mkdir -p "${portal_dir}"

if [[ -n "${LAB_PORTAL_GIT_URL}" ]]; then
  rm -rf "${portal_dir:?}"/*
  git clone "${LAB_PORTAL_GIT_URL}" "${portal_dir}"
else
  # Use local project content where this installer is located.
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  rsync -a --delete \
    --exclude '.git' \
    --exclude '.venv' \
    --exclude '__pycache__' \
    "${script_dir}/" "${portal_dir}/"
fi

cd "${portal_dir}"
python3 -m venv .venv
./.venv/bin/pip install --upgrade pip
./.venv/bin/pip install -r requirements.txt

read -r -p "Lab Portal bind port (default 8000): " LAB_PORT
LAB_PORT="${LAB_PORT:-8000}"
read -r -p "Guacamole base URL (default http://$(hostname -I | awk '{print $1}'):8080/guacamole): " GUAC_BASE_URL
GUAC_BASE_URL="${GUAC_BASE_URL:-http://$(hostname -I | awk '{print $1}'):8080/guacamole}"
read -r -p "TFTP root path (default /srv/tftp): " TFTP_ROOT_PATH
TFTP_ROOT_PATH="${TFTP_ROOT_PATH:-/srv/tftp}"
mkdir -p "${TFTP_ROOT_PATH}"

read -r -s -p "ELTEX_USERNAME (for submit checks): " ELTEX_USERNAME
echo ""
read -r -s -p "ELTEX_PASSWORD (for submit checks): " ELTEX_PASSWORD
echo ""
read -r -s -p "ELTEX_ENABLE_PASSWORD (optional, press Enter to skip): " ELTEX_ENABLE_PASSWORD
echo ""

SESSION_SECRET="$(openssl rand -hex 32 2>/dev/null || date +%s%N)"

cat > /etc/guac-lab-portal.env <<EOF
APP_SESSION_SECRET=${SESSION_SECRET}
GUACAMOLE_BASE_URL=${GUAC_BASE_URL}
TFTP_ROOT_PATH=${TFTP_ROOT_PATH}
SER2NET_TELNET_TIMEOUT_SEC=3
ELTEX_USERNAME=${ELTEX_USERNAME}
ELTEX_PASSWORD=${ELTEX_PASSWORD}
ELTEX_ENABLE_PASSWORD=${ELTEX_ENABLE_PASSWORD}
EOF
chmod 600 /etc/guac-lab-portal.env

cat > /etc/systemd/system/guac-lab-portal.service <<EOF
[Unit]
Description=Guacamole Lab Portal
After=network.target

[Service]
Type=simple
WorkingDirectory=${portal_dir}
EnvironmentFile=/etc/guac-lab-portal.env
ExecStart=${portal_dir}/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${LAB_PORT}
Restart=always
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now guac-lab-portal

host_ip="$(hostname -I | awk '{print $1}')"
echo ""
echo "======================================================================================================"
echo "INSTALLATION COMPLETE"
echo "Guacamole: http://${host_ip}:8080/guacamole"
echo "Lab Portal: http://${host_ip}:${LAB_PORT}"
echo "Default Login/Pass: guacadmin / guacadmin"
echo ""
echo "IMPORTANT: Change admin password after first login."
echo "Configured ${NUM_DEVICES} devices (ports 2001-$((2000 + NUM_DEVICES)))."
echo "Set real VID/PID/SERIAL values in /etc/udev/rules.d/99-usb-serial.rules."
echo "Lab Portal test users: admin/admin123 and student1/student123"
echo "======================================================================================================"
